IF DB_ID('QuanLyBanHang') IS NULL
BEGIN
    CREATE DATABASE [QuanLyBanHang]
END
GO

USE [master]
GO

ALTER DATABASE [QuanLyBanHang] SET RECOVERY SIMPLE
GO
ALTER DATABASE [QuanLyBanHang] SET MULTI_USER
GO
ALTER DATABASE [QuanLyBanHang] SET READ_WRITE
GO
